apiVersion: 1
datasources:
  - name: UrbanHeat PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: urbanheat
    user: urbanheat
    secureJsonData:
      password: urbanheat
    jsonData:
      sslmode: disable
      postgresVersion: 16
      timescaledb: false
    isDefault: true
